### ISSUE TITLE
Missing imports or dependencies

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-editor/GroupDocs.Editor-for-Java-Spring#7]
This issue is raised in https://forum.groupdocs.com/t/groupdocs-editor-git-hub-code-issue/8523
Hi,
Application gives an error of missing files when I try to run it in browser. Please have a look at the attached screenshot. 
![screenshot](https://user-images.githubusercontent.com/15940608/86778432-ccebd100-c073-11ea-9e7e-71c5d35df18f.png). Please take a look.
Thanks

**Comment by alexander-tyutyunnyk-a** [comment]
@atirtahirgroupdocs on the new version of GroupDocs.Editor-for-Java-Spring these errors are fixed
